/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposIndexRouteImport } from './routes/repos.index'
import { Route as ReportsReportIdRouteImport } from './routes/reports.$reportId'
import { Route as ReposOwnerRepoCommitsRouteImport } from './routes/repos.$owner.$repo.commits'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIndexRoute = ReposIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReposRoute,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => ReportsRoute,
} as any)
const ReposOwnerRepoCommitsRoute = ReposOwnerRepoCommitsRouteImport.update({
  id: '/$owner/$repo/commits',
  path: '/$owner/$repo/commits',
  getParentRoute: () => ReposRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRouteWithChildren
  '/repos': typeof ReposRouteWithChildren
  '/test': typeof TestRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/repos/': typeof ReposIndexRoute
  '/repos/$owner/$repo/commits': typeof ReposOwnerRepoCommitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRouteWithChildren
  '/test': typeof TestRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/repos': typeof ReposIndexRoute
  '/repos/$owner/$repo/commits': typeof ReposOwnerRepoCommitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports': typeof ReportsRouteWithChildren
  '/repos': typeof ReposRouteWithChildren
  '/test': typeof TestRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/repos/': typeof ReposIndexRoute
  '/repos/$owner/$repo/commits': typeof ReposOwnerRepoCommitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reports'
    | '/repos'
    | '/test'
    | '/reports/$reportId'
    | '/repos/'
    | '/repos/$owner/$repo/commits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reports'
    | '/test'
    | '/reports/$reportId'
    | '/repos'
    | '/repos/$owner/$repo/commits'
  id:
    | '__root__'
    | '/'
    | '/reports'
    | '/repos'
    | '/test'
    | '/reports/$reportId'
    | '/repos/'
    | '/repos/$owner/$repo/commits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  ReposRoute: typeof ReposRouteWithChildren
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/': {
      id: '/repos/'
      path: '/'
      fullPath: '/repos/'
      preLoaderRoute: typeof ReposIndexRouteImport
      parentRoute: typeof ReposRoute
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/repos/$owner/$repo/commits': {
      id: '/repos/$owner/$repo/commits'
      path: '/$owner/$repo/commits'
      fullPath: '/repos/$owner/$repo/commits'
      preLoaderRoute: typeof ReposOwnerRepoCommitsRouteImport
      parentRoute: typeof ReposRoute
    }
  }
}

interface ReportsRouteChildren {
  ReportsReportIdRoute: typeof ReportsReportIdRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsReportIdRoute: ReportsReportIdRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface ReposRouteChildren {
  ReposIndexRoute: typeof ReposIndexRoute
  ReposOwnerRepoCommitsRoute: typeof ReposOwnerRepoCommitsRoute
}

const ReposRouteChildren: ReposRouteChildren = {
  ReposIndexRoute: ReposIndexRoute,
  ReposOwnerRepoCommitsRoute: ReposOwnerRepoCommitsRoute,
}

const ReposRouteWithChildren = ReposRoute._addFileChildren(ReposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsRoute: ReportsRouteWithChildren,
  ReposRoute: ReposRouteWithChildren,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
